### ISSUE TITLE
Empty array when sync started without working JDK setup.

### ISSUE THREAD

**Issue by fboldog** [cbeust/kobalt-intellij-plugin#1]
Empty array (and ArrayIndexOutOfBoundsException) when sync started without working JDK setup.
https://github.com/cbeust/kobalt-intellij-plugin/blob/master/src/com/beust/kobalt/intellij/KobaltProjectComponent.kt#L190

```
java.lang.ArrayIndexOutOfBoundsException: 0
    at com.beust.kobalt.intellij.KobaltProjectComponent.launchServer(KobaltProjectComponent.kt:196)
    at com.beust.kobalt.intellij.KobaltProjectComponent.access$launchServer(KobaltProjectComponent.kt:51)
    at com.beust.kobalt.intellij.KobaltProjectComponent$syncBuildFile$$inlined$with$lambda$1.invoke(KobaltProjectComponent.kt:76)
    at com.beust.kobalt.intellij.KobaltProjectComponent$syncBuildFile$$inlined$with$lambda$1.invoke(KobaltProjectComponent.kt:51)
    at com.beust.kobalt.intellij.KobaltProjectComponent$toBackgroundTask$1.run(KobaltProjectComponent.kt:90)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by dmitry-zhuravlev** [comment]
Looks like outdated issue. `KobaltProjectComponent` changed significantly since the mentioned stacktrace.
