### ISSUE TITLE
Exception in Initializer when running a task

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#22]
I double clicked on the "run" task of the Kobalt project:

```
2016-05-05 01:38:19,979 [16377424]   WARN - nal.AbstractExternalSystemTask - java.lang.ExceptionInInitializerError 
com.intellij.openapi.externalSystem.model.ExternalSystemException: java.lang.ExceptionInInitializerError
    at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemTaskManagerWrapper.executeTasks(ExternalSystemTaskManagerWrapper.java:63)
    at com.intellij.openapi.externalSystem.service.internal.ExternalSystemExecuteTaskTask.doExecute(ExternalSystemExecuteTaskTask.java:127)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
    at com.intellij.openapi.externalSystem.service.execution.ExternalSystemRunConfiguration$MyRunnableState$1.run(ExternalSystemRunConfiguration.java:196)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java.lang.reflect.UndeclaredThrowableException
    at com.sun.proxy.$Proxy3.executeTasks(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
    at sun.rmi.transport.Transport$1.run(Transport.java:200)
    at sun.rmi.transport.Transport$1.run(Transport.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$256(TCPTransport.java:683)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:171)
    at com.sun.proxy.$Proxy158.executeTasks(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.execution.rmi.RemoteUtil.invokeRemote(RemoteUtil.java:124)
    at com.intellij.execution.rmi.RemoteUtil.access$100(RemoteUtil.java:36)
    at com.intellij.execution.rmi.RemoteUtil$2$1$1.compute(RemoteUtil.java:105)
    at com.intellij.execution.rmi.RemoteUtil.executeWithClassLoader(RemoteUtil.java:181)
    at com.intellij.execution.rmi.RemoteUtil$2$1.invoke(RemoteUtil.java:102)
    at com.sun.proxy.$Proxy158.executeTasks(Unknown Source)
    at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemTaskManagerWrapper.executeTasks(ExternalSystemTaskManagerWrapper.java:55)
    at com.intellij.openapi.externalSystem.service.internal.ExternalSystemExecuteTaskTask.doExecute(ExternalSystemExecuteTaskTask.java:127)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
    at com.intellij.openapi.externalSystem.service.execution.ExternalSystemRunConfiguration$MyRunnableState$1.run(ExternalSystemRunConfiguration.java:196)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.openapi.externalSystem.service.RemoteExternalSystemFacadeImpl$1.invoke(RemoteExternalSystemFacadeImpl.java:113)
    at com.sun.proxy.$Proxy3.executeTasks(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
    at sun.rmi.transport.Transport$1.run(Transport.java:200)
    at sun.rmi.transport.Transport$1.run(Transport.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$256(TCPTransport.java:683)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    ... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.beust.kobalt.intellij.task.KobaltTaskManager.prepareTaskExecutionParameters(KobaltTaskManager.kt:50)
    at com.beust.kobalt.intellij.task.KobaltTaskManager.executeTasks(KobaltTaskManager.kt:27)
    at com.beust.kobalt.intellij.task.KobaltTaskManager.executeTasks(KobaltTaskManager.kt:21)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemTaskManagerImpl$1.produce(RemoteExternalSystemTaskManagerImpl.java:56)
    at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemTaskManagerImpl.executeTasks(RemoteExternalSystemTaskManagerImpl.java:52)
    ... 23 more
Caused by: java.lang.ExceptionInInitializerError
    at com.intellij.openapi.vfs.LocalFileSystem.getInstance(LocalFileSystem.java:41)
    at com.beust.kobalt.intellij.DistributionDownloader.install(DistributionDownloader.kt:114)
    at com.beust.kobalt.intellij.DistributionDownloader$Companion.maybeDownloadAndInstallKobaltJarSilently(DistributionDownloader.kt:77)
    at com.beust.kobalt.intellij.KobaltApplicationComponent$Companion$kobaltJar$2$result$1.call(KobaltApplicationComponent.kt:59)
    at com.beust.kobalt.intellij.KobaltApplicationComponent$Companion$kobaltJar$2$result$1.call(KobaltApplicationComponent.kt:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    ... 3 more
Caused by: java.lang.NullPointerException
    at com.intellij.openapi.vfs.VirtualFileManager.getInstance(VirtualFileManager.java:51)
    at com.intellij.openapi.vfs.LocalFileSystem$LocalFileSystemHolder.<clinit>(LocalFileSystem.java:37)
    ... 9 more
```

**Comment by cbeust** [comment]
Note that this crash only happens on Kobalt and not a simpler project (e.g. Klaxon). Might be due to the fact that Kobalt has multiple modules?

The problem is at this line in `KobaltTaskManager`:

```
    private fun prepareTaskExecutionParameters(projectPath: String, taskNames: MutableList<String>): SimpleJavaParameters {
        val parameters = SimpleJavaParameters().apply {
            workingDirectory = projectPath
```

`projectPath` is being passed as the `Build.kt` path instead of the project's, but I'm not sure where that string is coming from since it's invoked by IDEA itself.

Also, for some reason, most of my breakpoints don't seem to work any more inside the plug-in.

**Comment by dmitry-zhuravlev** [comment]
I've checked and got another exception:

`WARN: Call GetDependencies for build file C:\Users\dzhuravl\IdeaProjects\kobalt\kobalt\src\Build.kt 
[  76908]   WARN - ution.rmi.RemoteProcessSupport - ERROR: Couldn't call getDependencies() on the server: <html><body><h2>500 Internal Error</h2></body></html>`

It seems that server always return 500 for kobalt build file. Tested on the latest kobalt-0.761.
Note that simple project works well but not kobalt project.

> Also, for some reason, most of my breakpoints don't seem to work any more inside the plug-in.

Yes, breakpoints will not work in some places because IDE execute that code in the external process.

**Comment by dmitry-zhuravlev** [comment]
Here is more detailed log from external server launched (without IDEA plugin):

`java -jar kobalt-0.761.jar --log 3 --force --dev --server
URL for core kobalt-plugin.xml: jar:file:/C:/Users/dzhuravl/.kobalt/wrapper/dist/kobalt-0.761/kobalt/wrapper/kobalt-0.761.jar!/META-INF/kobalt-core-plugin.xml
Parsed plugin XML file, found: kobalt
              __ __           __              __   __
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __`/  / /  / **/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_
          /_/ |_|  __**/ /_.___/ __,_/  /_/   __/  0.761

KobaltServer created C:\Users\dzhuravl.kobalt\kobaltServer.properties
KobaltServer listening on port 1236
BUILD SUCCESSFUL (1 seconds)
[Thread-2] INFO org.eclipse.jetty.util.log - Logging initialized @3631ms
Created .kobalt\versionCheckTimestamp.txt
[Thread-2] INFO spark.webserver.JettySparkServer - == Spark has ignited ...
[Thread-2] INFO spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:1236
[Thread-2] INFO org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
[Thread-2] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@76ccefa7{HTTP/1.1,[http/1.1]}{0.0.0.0:1236}
[Thread-2] INFO org.eclipse.jetty.server.Server - Started @3774ms
Created .kobalt\versionCheckTimestamp.txt
L/12:37:05.990 [qtp1451756527-20] ParsedBuildFile - Saved C:\Users\dzhuravl\AppData\Local\Temp\kobalt6697201503641291458.kt
L/12:37:05.992 [qtp1451756527-20] Companion - Script jar file: C:\Users\dzhuravl\IdeaProjects\kobalt.kobalt\build\preBuildScript.jar
L/12:37:06.007 [qtp1451756527-20] Companion - Script jar file: C:\Users\dzhuravl\IdeaProjects\kobalt.kobalt\build\buildScript.jar
L/12:37:06.014 [qtp1451756527-20] Companion - Created C:\Users\dzhuravl\AppData\Local\Temp\kobalt4594955230586144774.kt
L/12:37:06.015 [qtp1451756527-20] BuildFileCompiler - Running build file Modified Build.kt jar: C:\Users\dzhuravl\IdeaProjects\kobalt.kobalt\build\buildScript.jar
L/12:37:06.017 [qtp1451756527-20] BuildFileCompiler -   Build file is up to date
[qtp1451756527-20] ERROR spark.webserver.MatcherFilter -
java.util.NoSuchElementException: No element matching predicate was found.
        at Kobalt114115034447143747Kt.readVersion(kobalt114115034447143747.kt:224)
        at Kobalt114115034447143747Kt$wrapper$1.invoke(kobalt114115034447143747.kt:37)
        at Kobalt114115034447143747Kt$wrapper$1.invoke(kobalt114115034447143747.kt)
        at com.beust.kobalt.DirectivesKt.project(Directives.kt:11)
        at Kobalt114115034447143747Kt.<clinit>(kobalt114115034447143747.kt:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.beust.kobalt.app.BuildScriptUtil.runBuildScriptJarFile(BuildScriptUtil.kt:83)
        at com.beust.kobalt.app.BuildFileCompiler.findProjects(BuildFileCompiler.kt:93)
        at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:57)
        at com.beust.kobalt.Main.initForBuildFile(Main.kt:230)
        at com.beust.kobalt.Main.access$initForBuildFile(Main.kt:55)
        at com.beust.kobalt.Main$runWithArgs$port$1.invoke(Main.kt:162)
        at com.beust.kobalt.Main$runWithArgs$port$1.invoke(Main.kt:55)
        at com.beust.kobalt.app.remote.SparkServer$run$2.handle(SparkServer.kt:34)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Unknown Source)
`

@cbeust Seems the old one problem with "matching predicate" Any ideas?

**Comment by cbeust** [comment]
This seems to be happening in the `readVersion()` function of the build
file, but I don't see what could be throwing this `matching predicate`
error in that function:

```
@Task(name = "copyVersionForWrapper", runBefore = arrayOf("assemble"),
runAfter = arrayOf("compile"), description = "")
fun taskCopyVersionForWrapper(project: Project) : TaskResult {
    if (project.name == "kobalt-wrapper") {
        val toString = "modules/wrapper/kobaltBuild/classes"
        File(toString).mkdirs()
        val from = Paths.get("src/main/resources/kobalt.properties")
        val to = Paths.get("$toString/kobalt.properties")
        Files.copy(from,
                to,
                StandardCopyOption.REPLACE_EXISTING)
    }
    return TaskResult()
}
```

## 

Cédric

**Comment by cbeust** [comment]
Can you just comment out the `@Task` in the build file and try again? This
way this task will no longer run and we'll see if this fixes the problem.
If it does, then we know for sure this function is the problem.

## 

Cédric

**Comment by dmitry-zhuravlev** [comment]
Commenting out @Task doesn't help. But commenting out readVersion() seems to do the trick. However still not succeed because I have "Socket read timeout" exception since internet connection very slow to get all dependencies for the Kobalt project. I'll recheck it with a good connection.

**Comment by cbeust** [comment]
That's very strange, if you remove @Task than `readVersion` should no
longer be invoked...

## 

Cédric

**Comment by cbeust** [comment]
Oh wait of course it gets invoked from other tasks...

```
val wrapper = project {
    name = "kobalt-wrapper"
    group = "com.beust"
    artifactId = name
    version = readVersion()
```

## 

Cédric

**Comment by dmitry-zhuravlev** [comment]
Yes, I comment out "readVersion()" and all it's calling from project{} and after second reimport it works!

**Comment by cbeust** [comment]
Ok so I'll debug what's wrong with readVersion().

Is that what's causing the Exception In Initializer?

## 

Cédric

**Comment by dmitry-zhuravlev** [comment]
Checked "run" execution and it also works. Please recheck because I made some changes in TaskManager.

**Comment by cbeust** [comment]
I haven't seen any changes from you in `TaskManager`, did you send a PR?

The bug in `readVersion()` is probably coming from `first()` but I can't test that since I get the initializer error even before the build file is run.

**Comment by cbeust** [comment]
Ok I pulled your changes but still seeing the initializer error (and still not seeing the `readVersion` error you are seeing).

**Comment by dmitry-zhuravlev** [comment]
Just tried the same on another machine: It seems that 'readVersion' not a root of the problem. Because comment it out doesn't solve the problem. 
But if I start server like standalone one "java -jar kobalt-07..." and try to get dependencies - all works.
And after kill standalone one and run from plugin it also works even with "readVersion" function.... some mystic problem... And I don't have initializer error.

**Comment by cbeust** [comment]
Note that I made a bunch of improvements in both kobalt and the plug-in, which should solve some errors we've been seeing (not sure about this specific one). Make sure you pull the latest.

**Comment by dmitry-zhuravlev** [comment]
Looks like an obsolete issue.
