### ISSUE TITLE
When a kobalt.jar is downloaded, start a new server

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#27]
I added a new "quit" command to the server:

https://github.com/cbeust/kobalt/blob/master/src/main/kotlin/com/beust/kobalt/app/remote/SparkServer.kt#L32

Whenever the plug-in downloads a new kobalt.jar file, it should:
- Send a "quit" to the existing server
- Start a new server with the jar file that was just downloaded

This should fix a few problems we've seen with trying to contact old servers and also with servers lingering around.

**Comment by dmitry-zhuravlev** [comment]
@cbeust It seems that simple `Spark.stop()` isn't enough... If I call with retrofit this method it produce:

`[  48171]  ERROR - ellij.project.impl.ProjectImpl - Failed to connect to localhost/0:0:0:0:0:0:0:1:1246 
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:1246
    at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:142)
    at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
    at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
    at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
    at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
    at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
    at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
    at okhttp3.RealCall.getResponse(RealCall.java:240)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
    at okhttp3.RealCall.execute(RealCall.java:57)`

You should response first, before executing `Spark.stop()`

**Comment by cbeust** [comment]
Ah good point.

## 

Cédric

**Comment by cbeust** [comment]
Mmmh there seem to be various issues when trying to shut down a Spark Server (e.g. https://groups.google.com/forum/#!topic/sparkjava/7NKAHbV92so )

Calling `stop()` before responding fails and obviously, you can't do it the other way around. The following hack appears to work but it's pretty ugly:

```
        Spark.get("/quit", { req, res ->
            Executors.newFixedThreadPool(1).let { executor ->
                executor.submit {
                    Thread.sleep(1000)
                    Spark.stop()
                    executor.shutdown()
                }
                "ok"
            }
        })
```

**Comment by cbeust** [comment]
The code above is now in the latest Kobalt.
