### ISSUE TITLE
Error when starting, building, executing and any kobalt related action.

### ISSUE THREAD

**Issue by sostrack** [cbeust/kobalt-intellij-plugin#31]
Hello, 

I have a few issues when running the kobalt plugin on intellij. 
On launch, and on any operation I get a **"Unable to save settings. Failed to save. Please restart IntelliJ Idea"** error

I also have the following problem when running the kobalt plugin on intellij:

```
String index out of range: 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at com.intellij.configurationStore.ProjectStateStorageManager.expandMacros(ProjectStateStorageManager.kt:33)
    at com.intellij.configurationStore.StateStorageManagerImpl.createStateStorage(StateStorageManagerImpl.kt:194)
    at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage(StateStorageManagerImpl.kt:150)
    at com.intellij.configurationStore.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.kt:133)
    at com.intellij.configurationStore.ComponentStoreImpl.initPersistentComponent(ComponentStoreImpl.kt:269)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
    at com.beust.kobalt.intellij.settings.KobaltSettings.getInstance(KobaltSettings.java:34)
    at com.beust.kobalt.intellij.manager.KobaltManager$getSettingsProvider$1.fun(KobaltManager.kt:128)
    at com.beust.kobalt.intellij.manager.KobaltManager$getSettingsProvider$1.fun(KobaltManager.kt:43)
    at com.intellij.openapi.externalSystem.service.settings.AbstractExternalSystemToolWindowCondition.value(AbstractExternalSystemToolWindowCondition.java:48)
    at com.intellij.openapi.externalSystem.service.settings.AbstractExternalSystemToolWindowCondition.value(AbstractExternalSystemToolWindowCondition.java:31)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$11.computeInReadAction(ToolWindowManagerImpl.java:502)
    at com.intellij.openapi.progress.util.ReadTask$1.run(ReadTask.java:52)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:951)
    at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:49)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.run(ProgressIndicatorUtils.java:205)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:201)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:43)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$6$2.run(ProgressIndicatorUtils.java:180)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by cbeust** [comment]
Ping @dmitry-zhuravlev

**Comment by dmitry-zhuravlev** [comment]
Hello @sostrack
Seems like duplication of https://github.com/cbeust/kobalt/issues/201 
Still not recommend to use --init idea because it generates some old format.
Consider to use IDEA wizzard like explained in https://github.com/cbeust/kobalt/issues/201 
or you could do the following:
1) kobaltw --init kotlin
2) Open project with IDEA and then import detached Kobalt project:
![image](https://cloud.githubusercontent.com/assets/6297697/15501235/29834d2e-21b5-11e6-8fab-637a5d597869.png)

**Comment by dmitry-zhuravlev** [comment]
FYI created https://github.com/cbeust/kobalt/issues/208
