### ISSUE TITLE
AssertionError when syncing

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#34]
Syncing produces:

```
5:11 PM AssertionError: Kotlin library should exists when adding sources root
```

The error message has an error ("exists" instead of "exist") but it seems to come from IDEA itself, not the Kobalt plug-in.

Also, each sync causes the "Kotlin not configured" banner to appear and I end up having to click the hyperlink to re-configure it. I'm using the latest 2016.2.

The full stack trace:

```
Kotlin library should exists when adding sources root
java.lang.AssertionError: Kotlin library should exists when adding sources root
    at org.jetbrains.kotlin.idea.configuration.KotlinWithLibraryConfigurator.configureModuleWithLibrary(KotlinWithLibraryConfigurator.java:142)
    at org.jetbrains.kotlin.idea.configuration.KotlinWithLibraryConfigurator.configure(KotlinWithLibraryConfigurator.java:111)
    at org.jetbrains.kotlin.idea.configuration.KotlinSetupEnvironmentNotificationProvider$Companion$createConfiguratorsPopup$step$1.onChosen(KotlinSetupEnvironmentNotificationProvider.kt:128)
    at org.jetbrains.kotlin.idea.configuration.KotlinSetupEnvironmentNotificationProvider$Companion$createConfiguratorsPopup$step$1.onChosen(KotlinSetupEnvironmentNotificationProvider.kt:121)
    at com.intellij.ui.popup.list.ListPopupImpl.a(ListPopupImpl.java:399)
    at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:351)
    at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:504)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.Component.processMouseEvent(Component.java:6527)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:573)
    at java.awt.Component.processEvent(Component.java:6292)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4883)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4705)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4705)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:719)
    at java.awt.EventQueue$4.run(EventQueue.java:717)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:822)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:653)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by dmitry-zhuravlev** [comment]
> each sync causes the "Kotlin not configured" banner to appear

Actyally this checking happens asynchronously and could happen before Build.kt module configured. This can be simple ignored if the Build.kt module configured properly.

But assertion problem looks not good. Do you have some steps how to reproduce it?

**Comment by cbeust** [comment]
I'm trying to sync and build `http://github.com/cbeust/klaxon` when this happens. And actually, I'm seeing a different error now trying to reproduce this problem, I'll file a separate issue.

**Comment by cbeust** [comment]
Done: https://github.com/cbeust/kobalt-intellij-plugin/issues/37
