### ISSUE TITLE
"SDK should be configured" error when syncing

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#37]
Trying to sync http://github.com/beust/klaxon always produces:

```
D:\Java\jdk1.8.0_05\bin\java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:55431,suspend=y,server=n -Xmx512m -Xms256m -XX:MaxPermSize=250m -ea "-Xbootclasspath/a:C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\boot.jar" -Didea.config.path=C:\Users\cbeust\.IntelliJIdea2016.1\system\plugins-sandbox\config -Didea.system.path=C:\Users\cbeust\.IntelliJIdea2016.1\system\plugins-sandbox\system -Didea.plugins.path=C:\Users\cbeust\.IntelliJIdea2016.1\system\plugins-sandbox\plugins -Didea.classpath.index.enabled=false -Didea.required.plugins.id=com.beust.kobalt.intellij -Dfile.encoding=windows-1252 -classpath "D:\Java\jdk1.8.0_05\lib\tools.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\idea_rt.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\idea.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\bootstrap.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\extensions.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\util.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\openapi.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\trove4j.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\jdom.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 162.426.1\lib\log4j.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 162.426.1\lib\idea_rt.jar" com.intellij.idea.Main
Connected to the target VM, address: '127.0.0.1:55431', transport: 'socket'
May 30, 2016 7:02:54 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[   6017]   WARN - .intellij.diagnostic.VMOptions - VM options file path missing 
[  27241]   WARN - ution.rmi.RemoteProcessSupport - WARN: Kobalt jar: C:\Users\cbeust\.kobalt\wrapper\dist\kobalt-0.755\kobalt\wrapper\kobalt-0.755.jar 
[  27263]   WARN - ution.rmi.RemoteProcessSupport - WARN: Server parameters: com.intellij.execution.configurations.SimpleJavaParameters@3be898fc 
[  27279]   WARN - nal.AbstractExternalSystemTask - SDK should be defined 
com.intellij.openapi.externalSystem.model.ExternalSystemException: SDK should be defined
    at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:59)
    at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:419)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4$2.run(ExternalSystemUtil.java:500)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:608)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:472)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:132)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:332)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java.lang.reflect.UndeclaredThrowableException
    at com.sun.proxy.$Proxy3.resolveProjectInfo(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
    at sun.rmi.transport.Transport$1.run(Transport.java:178)
    at sun.rmi.transport.Transport$1.run(Transport.java:175)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:174)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:557)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:812)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:671)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:194)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:148)
    at com.sun.proxy.$Proxy118.resolveProjectInfo(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.execution.rmi.RemoteUtil.invokeRemote(RemoteUtil.java:124)
    at com.intellij.execution.rmi.RemoteUtil.access$100(RemoteUtil.java:36)
    at com.intellij.execution.rmi.RemoteUtil$2$1$1.compute(RemoteUtil.java:105)
    at com.intellij.execution.rmi.RemoteUtil.executeWithClassLoader(RemoteUtil.java:181)
    at com.intellij.execution.rmi.RemoteUtil$2$1.invoke(RemoteUtil.java:102)
    at com.sun.proxy.$Proxy118.resolveProjectInfo(Unknown Source)
    at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
    at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:419)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4$2.run(ExternalSystemUtil.java:500)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:608)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:472)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:132)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:332)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.openapi.externalSystem.service.RemoteExternalSystemFacadeImpl$1.invoke(RemoteExternalSystemFacadeImpl.java:113)
    at com.sun.proxy.$Proxy3.resolveProjectInfo(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
    at sun.rmi.transport.Transport$1.run(Transport.java:178)
    at sun.rmi.transport.Transport$1.run(Transport.java:175)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:174)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:557)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:812)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:671)
    ... 3 more
Caused by: java.lang.IllegalArgumentException: SDK should be defined
    at com.intellij.execution.configurations.SimpleJavaParameters.toCommandLine(SimpleJavaParameters.java:115)
    at com.beust.kobalt.intellij.server.ServerUtil$Companion.launchServer(ServerUtil.kt:124)
    at com.beust.kobalt.intellij.DependenciesProcessor.sendGetDependencies(DependenciesProcessor.kt:28)
    at com.beust.kobalt.intellij.DependenciesProcessor.run(DependenciesProcessor.kt:18)
    at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.resolveProjectInfo(KobaltProjectResolver.kt:40)
    at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.resolveProjectInfo(KobaltProjectResolver.kt:25)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:41)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:37)
    at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
    ... 21 more

```

**Comment by cbeust** [comment]
That's weird:

```
[  53186]   WARN - ution.rmi.RemoteProcessSupport - WARN: Kobalt jar: 
C:\Users\cbeust\.kobalt\wrapper\dist\kobalt-0.755\kobalt\wrapper\kobalt-0.755.jar 
```

Why would it be using such an old version? The minimum is much higher:

```
        val MIN_KOBALT_VERSION = "0.786"
```

**Comment by dmitry-zhuravlev** [comment]
Hm... Which state do you have in "Auto download Kobalt" checkbox? Can be found in Settings-> Build tools -> Kobalt. If this checkbox unchecked that means that some old version (configured previously) will taken.

Regarding "SDK not found" I'll try to reproduce...

**Comment by dmitry-zhuravlev** [comment]
"SDK not found" problem relates only for EAP builds. But solutions can be applied also to the release branch.
