### ISSUE TITLE
KobaltProjectComponent throws kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by antonarhipov** [cbeust/kobalt-intellij-plugin#4]
When opening a project that was initialized with Kobalt, an exception is thrown.
Plugin version: 1.35

com.beust.kobalt.intellij.KobaltProjectComponent@76890016
kotlin.KotlinNullPointerException
    at com.beust.kobalt.intellij.BuildModule.addBuildModule(BuildModule.kt:69)
    at com.beust.kobalt.intellij.BuildModule.maybeAddBuildModule(BuildModule.kt:28)
    at com.beust.kobalt.intellij.BuildModule.run(BuildModule.kt:22)
    at com.beust.kobalt.intellij.KobaltProjectComponent.projectOpened(KobaltProjectComponent.kt:30)
    at com.intellij.openapi.project.impl.ProjectImpl.b(ProjectImpl.java:400)
    at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:63)
    at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:434)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:98)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:721)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:352)
    at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:220)
    at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:93)
    at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:128)
    at com.intellij.ide.actions.OpenFileAction.a(OpenFileAction.java:88)
    at com.intellij.ide.actions.OpenFileAction.access$000(OpenFileAction.java:50)
    at com.intellij.ide.actions.OpenFileAction$1.consume(OpenFileAction.java:68)
    at com.intellij.ide.actions.OpenFileAction$1.consume(OpenFileAction.java:58)
    at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:159)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:111)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:89)
    at com.intellij.ide.actions.OpenFileAction.actionPerformed(OpenFileAction.java:58)
    at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:64)
    at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:106)
    at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:77)
    at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:277)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dmitry-zhuravlev** [comment]
`com.beust.kobalt.intellij.BuildModule` was deprecated and not used anymore. 
Probably I can close this issue. 
@antonarhipov Thanks for filling this issue! If you see any problems you are always welcome to fill some issue again ;)
