### ISSUE TITLE
Could not build: Couldn't resolve org.jetbrains.kotlin:kotlin-stdlib:1.0.0-beta-4584

### ISSUE THREAD

**Issue by juherr** [cbeust/kobalt-intellij-plugin#5]
```
Could not build: Couldn't resolve org.jetbrains.kotlin:kotlin-stdlib:1.0.0-beta-4584
java.lang.IllegalStateException: Could not build: Couldn't resolve org.jetbrains.kotlin:kotlin-stdlib:1.0.0-beta-4584
    at kotlin.PreconditionsKt__PreconditionsKt.error(Preconditions.kt:142)
    at kotlin.PreconditionsKt.error(Unknown Source)
    at com.beust.kobalt.intellij.SyncBuildFileAction$sendGetDependencies$1.run(SyncBuildFileAction.kt:152)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:957)
    at com.beust.kobalt.intellij.SyncBuildFileAction.sendGetDependencies(SyncBuildFileAction.kt:131)
    at com.beust.kobalt.intellij.SyncBuildFileAction.access$sendGetDependencies(SyncBuildFileAction.kt:32)
    at com.beust.kobalt.intellij.SyncBuildFileAction$run$$inlined$with$lambda$2.invoke(SyncBuildFileAction.kt:61)
    at com.beust.kobalt.intellij.SyncBuildFileAction$run$$inlined$with$lambda$2.invoke(SyncBuildFileAction.kt:32)
    at com.beust.kobalt.intellij.SyncBuildFileAction$toBackgroundTask$1.run(SyncBuildFileAction.kt:69)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:376)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)



com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:913)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:861)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:844)
    at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:786)
    at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:776)
    at com.intellij.util.indexing.FileBasedIndexImpl.getAllKeys(FileBasedIndexImpl.java:770)
    at org.jetbrains.kotlin.idea.versions.KotlinRuntimeLibraryUtilKt.getLibraryRootsWithAbiIncompatibleVersion(KotlinRuntimeLibraryUtil.kt:226)
    at org.jetbrains.kotlin.idea.versions.KotlinRuntimeLibraryUtilKt.getLibraryRootsWithAbiIncompatibleKotlinClasses(KotlinRuntimeLibraryUtil.kt:54)
    at org.jetbrains.kotlin.idea.versions.UnsupportedAbiVersionNotificationPanelProvider$Companion.collectBadRoots(UnsupportedAbiVersionNotificationPanelProvider.kt:209)
    at org.jetbrains.kotlin.idea.configuration.KotlinSetupEnvironmentNotificationProvider.createNotificationPanel(KotlinSetupEnvironmentNotificationProvider.kt:76)
    at org.jetbrains.kotlin.idea.configuration.KotlinSetupEnvironmentNotificationProvider.createNotificationPanel(KotlinSetupEnvironmentNotificationProvider.kt:47)
    at com.intellij.ui.EditorNotificationsImpl$4.performInReadAction(EditorNotificationsImpl.java:146)
    at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
    at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:973)
    at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:220)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:216)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:162)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:159)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:216)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$6$2.run(ProgressIndicatorUtils.java:181)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:172)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

-----------
Indexing started at:
java.lang.Throwable
    at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:165)
    at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:90)
    at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:298)
    at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.b(ProjectRootManagerImpl.java:421)
    at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:57)
    at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.a(ProjectRootManagerImpl.java:114)
    at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:127)
    at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:326)
    at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.b(ProjectRootManagerImpl.java:245)
    at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.setProjectSdk(ProjectRootManagerImpl.java:241)
    at com.intellij.ide.util.projectWizard.JdkChooserPanel$5.run(JdkChooserPanel.java:248)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1016)
    at com.intellij.ide.util.projectWizard.JdkChooserPanel.chooseAndSetJDK(JdkChooserPanel.java:246)
    at com.intellij.openapi.roots.ui.configuration.IdeaProjectSettingsService.chooseAndSetSdk(IdeaProjectSettingsService.java:164)
    at com.android.tools.idea.gradle.structure.editors.AndroidProjectSettingsService.chooseAndSetSdk(AndroidProjectSettingsService.java:226)
    at org.jetbrains.kotlin.idea.configuration.KotlinSetupEnvironmentNotificationProvider$Companion$createSetupSdkPanel$$inlined$apply$lambda$1.run(KotlinSetupEnvironmentNotificationProvider.kt:90)
    at com.intellij.ui.EditorNotificationPanel$2.hyperlinkActivated(EditorNotificationPanel.java:92)
    at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:28)
    at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:194)
    at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:127)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I'm behind an http proxy and IntelliJ has its configuration.

**Comment by dmitry-zhuravlev** [comment]
@juherr  `SyncBuildFileAction` deprecated and not used any more in the latest plugin. With the latest Kobalt and IDEA plugin consider to use proxy configuration also for Kobalt itself. See HTTP proxy settings here:  http://beust.com/kobalt/documentation/index.html

**Comment by juherr** [comment]
@dmitry-zhuravlev Ok, thanks for the answer.

> With the latest Kobalt and IDEA plugin consider to use proxy configuration also for Kobalt itself. See HTTP proxy settings

Does it mean `IDEA plugin` will use settings from `settings.xml` or from the IDEA settings? Both, with a fallback from one to the other, could be a good idea IMO :)

**Comment by dmitry-zhuravlev** [comment]
> Does it mean IDEA plugin will use settings from settings.xml

No. IDEA plugin uses proxy settings specified in IDEA but Kobalt have their own settings and use it from `settings.xml`

> with a fallback from one to the other

For the first glance looks attractive :)
But this "magic" fallback from one to another could confuse users and also complicates workflow of integration between IDEA plugin and Kobalt.
Here we should be more consistent to other build systems like Maven and Gradle:
The proxy settings for build tool and proxy settings for IDE plugins doesn't intersect.

**Comment by juherr** [comment]
Ok, looks good. Thanks for the answer :)
