### ISSUE TITLE
NoClassDefFoundError: com/android/ide/common/rendering/api/Bridge

### ISSUE THREAD

**Issue by orangy** [cbeust/kobalt-intellij-plugin#57]
com/android/ide/common/rendering/api/Bridge
java.lang.NoClassDefFoundError: com/android/ide/common/rendering/api/Bridge
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:269)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:265)
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:219)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at android.os.SystemProperties_Delegate.native_get(SystemProperties_Delegate.java:43)
    at android.os.SystemProperties.native_get(SystemProperties.java)
    at android.os.SystemProperties.get(SystemProperties.java:64)
    at android.os.Build.getString(Build.java:819)
    at android.os.Build.<clinit>(Build.java:39)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at retrofit2.Platform.findPlatform(Platform.java:37)
    at retrofit2.Platform.<clinit>(Platform.java:29)
    at retrofit2.Retrofit$Builder.<init>(Retrofit.java:402)
    at com.beust.kobalt.intellij.server.ServerFacade.buildService(ServerFacade.kt:44)
    at com.beust.kobalt.intellij.server.ServerFacade.sendPingCommand(ServerFacade.kt:33)
    at com.beust.kobalt.intellij.server.ServerUtil$Companion.isServerRunning(ServerUtil.kt:88)
    at com.beust.kobalt.intellij.server.ServerUtil$Companion.sendQuitCommand(ServerUtil.kt:146)
    at com.beust.kobalt.intellij.server.ServerUtil$Companion.stopServer(ServerUtil.kt:101)
    at com.beust.kobalt.intellij.KobaltProjectComponent.projectClosed(KobaltProjectComponent.kt:34)
    at com.intellij.openapi.project.impl.ProjectImpl.b(ProjectImpl.java:400)
    at com.intellij.openapi.project.impl.ProjectImpl.access$300(ProjectImpl.java:69)
    at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectClosed(ProjectImpl.java:428)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectClosed(ProjectManagerImpl.java:99)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.g(ProjectManagerImpl.java:668)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:567)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:927)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:564)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:588)
    at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:88)
    at com.intellij.ide.actions.CloseProjectAction.actionPerformed(CloseProjectAction.java:35)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.e(IdeKeyEventDispatcher.java:477)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.android.ide.common.rendering.api.Bridge
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:215)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 51 more

**Comment by suchengjian** [comment]
I solve the problem when i change the compileSdkVersion 23 to 22
