### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sargunv** [cbeust/kobalt-intellij-plugin#6]
Happens ~~whenever~~ sometimes when I sync the Kobalt build file on any Kobalt project:

```
0
java.lang.ArrayIndexOutOfBoundsException: 0
    at com.beust.kobalt.intellij.SyncBuildFileAction.launchServer(SyncBuildFileAction.kt:196)
    at com.beust.kobalt.intellij.SyncBuildFileAction.access$launchServer(SyncBuildFileAction.kt:32)
    at com.beust.kobalt.intellij.SyncBuildFileAction$run$$inlined$with$lambda$1.invoke(SyncBuildFileAction.kt:55)
    at com.beust.kobalt.intellij.SyncBuildFileAction$run$$inlined$with$lambda$1.invoke(SyncBuildFileAction.kt:32)
    at com.beust.kobalt.intellij.SyncBuildFileAction$toBackgroundTask$1.run(SyncBuildFileAction.kt:69)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by sargunv** [comment]
Seems to be a duplicate of #1
