### ISSUE TITLE
Crash when using the plug-in built with Kotlin 1.1

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#64]
I get the following exception on start up with a plug-in built with 1.1. Is this because the `kotlin-reflect.jar` and other libraries in the IDEA distribution are pre 1.1?

@dmitry-zhuravlev, any way to fix this?

If not, could you create a .zip compiled with 1.0.6 that I could deploy to the store?

Thanks!

```
java.lang.NoClassDefFoundError: Could not initialize class com.beust.kobalt.intellij.Constants
	at com.beust.kobalt.intellij.manager.KobaltManager.getSystemId(KobaltManager.kt:155)
	at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.getManager(ExternalSystemApiUtil.java:217)
	at org.jetbrains.plugins.gradle.service.GradleBuildClasspathManager.reload(GradleBuildClasspathManager.java:65)
	at org.jetbrains.plugins.gradle.service.project.GradleStartupActivity.configureBuildClasspath(GradleStartupActivity.java:80)
	at org.jetbrains.plugins.gradle.service.project.GradleStartupActivity.runActivity(GradleStartupActivity.java:60)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:146)
	at com.intellij.ide.startup.impl.StartupManagerImpl.d(StartupManagerImpl.java:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:160)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:159)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:372)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by dmitry-zhuravlev** [comment]
Seems like broken build.... Which branch do you trying to build?

Yep, I can build zip archive for 1.0.6 version but I think it couldn't be used with the latest version of Kobalt.
This is moustly because Build.kt will be all "red" (see https://github.com/cbeust/kobalt/issues/317)
The latest version of Kobalt API will be under 1.1 so it cannot be used with 1.0.6 version of Kotlin plugin in IDEA.

**Comment by cbeust** [comment]
Ideed, must have been a build problem: I just deployed 1.121 to the JetBrains site from my Windows laptop this time and everything seems to work fine. Can you try it and confirm?

Glad we're all on 1.1 now.

Thanks!
