### ISSUE TITLE
Couldn't connect to server on port 1234

### ISSUE THREAD

**Issue by sargunv** [cbeust/kobalt-intellij-plugin#7]
~~Happens whenever I open the Build.kt on any Kobalt project.~~
Happens when I sync the Kobalt build file now...

```
Couldn't connect to server on port 1234
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.beust.kobalt.intellij.SyncBuildFileAction.sendGetDependencies(SyncBuildFileAction.kt:175)
    at com.beust.kobalt.intellij.SyncBuildFileAction.access$sendGetDependencies(SyncBuildFileAction.kt:32)
    at com.beust.kobalt.intellij.SyncBuildFileAction$run$$inlined$with$lambda$2.invoke(SyncBuildFileAction.kt:61)
    at com.beust.kobalt.intellij.SyncBuildFileAction$run$$inlined$with$lambda$2.invoke(SyncBuildFileAction.kt:32)
    at com.beust.kobalt.intellij.SyncBuildFileAction$toBackgroundTask$1.run(SyncBuildFileAction.kt:69)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by sargunv** [comment]
```
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 192. ProviderInstanceBinding{key=Key[type=org.apache.maven.plugin.LegacySupport, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.plugin.internal.DefaultLegacySupport from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 193. ProviderInstanceBinding{key=Key[type=org.sonatype.aether.impl.MetadataGeneratorFactory, annotation=@com.google.inject.name.Named(value=versions)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.repository.internal.VersionsMetadataGeneratorFactory from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 194. ProviderInstanceBinding{key=Key[type=org.apache.maven.toolchain.ToolchainsBuilder, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.toolchain.DefaultToolchainsBuilder from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 195. ProviderInstanceBinding{key=Key[type=org.apache.maven.archetype.source.ArchetypeDataSource, annotation=@com.google.inject.name.Named(value=remote-catalog)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.archetype.source.RemoteCatalogArchetypeDataSource from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 196. ProviderInstanceBinding{key=Key[type=org.apache.maven.lifecycle.mapping.LifecycleMapping, annotation=@com.google.inject.name.Named(value=ejb)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.lifecycle.mapping.DefaultLifecycleMapping$__plexus6 from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 197. ProviderInstanceBinding{key=Key[type=org.sonatype.nexus.index.context.IndexCreator, annotation=@com.google.inject.name.Named(value=jarContent)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.sonatype.nexus.index.creator.JarFileContentsIndexCreator from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 198. ProviderInstanceBinding{key=Key[type=org.apache.maven.archetype.common.ArchetypeArtifactManager, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.archetype.common.DefaultArchetypeArtifactManager from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 199. ProviderInstanceBinding{key=Key[type=org.apache.maven.lifecycle.internal.LifecycleTaskSegmentCalculator, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 200. ProviderInstanceBinding{key=Key[type=org.sonatype.nexus.artifact.GavCalculator, annotation=@com.google.inject.name.Named(value=maven1)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.sonatype.nexus.artifact.M1GavCalculator from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 201. ProviderInstanceBinding{key=Key[type=org.sonatype.nexus.artifact.GavCalculator, annotation=@com.google.inject.name.Named(value=maven2)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.sonatype.nexus.artifact.M2GavCalculator from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 202. ProviderInstanceBinding{key=Key[type=org.sonatype.aether.impl.VersionResolver, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.repository.internal.DefaultVersionResolver from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 203. ProviderInstanceBinding{key=Key[type=org.apache.maven.project.ProjectDependenciesResolver, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.project.DefaultProjectDependenciesResolver from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 204. ProviderInstanceBinding{key=Key[type=org.apache.maven.lifecycle.mapping.LifecycleMapping, annotation=@com.google.inject.name.Named(value=pom)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.lifecycle.mapping.DefaultLifecycleMapping from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 205. ProviderInstanceBinding{key=Key[type=org.apache.maven.plugin.PluginDescriptorCache, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.plugin.DefaultPluginDescriptorCache from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 206. ProviderInstanceBinding{key=Key[type=org.sonatype.nexus.index.QueryCreator, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.sonatype.nexus.index.DefaultQueryCreator from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 207. ProviderInstanceBinding{key=Key[type=org.sonatype.aether.impl.MetadataGeneratorFactory, annotation=@com.google.inject.name.Named(value=snapshot)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.repository.internal.SnapshotMetadataGeneratorFactory from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 208. ProviderInstanceBinding{key=Key[type=org.apache.maven.artifact.factory.ArtifactFactory, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.artifact.factory.DefaultArtifactFactory from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 209. ProviderInstanceBinding{key=Key[type=org.apache.maven.plugin.PluginManager, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.plugin.internal.DefaultPluginManager from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 210. ProviderInstanceBinding{key=Key[type=org.sonatype.nexus.index.treeview.IndexTreeView, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.sonatype.nexus.index.treeview.DefaultIndexTreeView from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 211. ProviderInstanceBinding{key=Key[type=org.sonatype.aether.impl.ArtifactResolver, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.sonatype.aether.impl.internal.DefaultArtifactResolver from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 212. ProviderInstanceBinding{key=Key[type=org.apache.maven.model.plugin.PluginConfigurationExpander, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.model.plugin.DefaultPluginConfigurationExpander from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 213. ProviderInstanceBinding{key=Key[type=org.apache.maven.model.path.ModelUrlNormalizer, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.model.path.DefaultModelUrlNormalizer from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 214. ProviderInstanceBinding{key=Key[type=org.apache.maven.artifact.handler.ArtifactHandler, annotation=@com.google.inject.name.Named(value=ear)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.artifact.handler.DefaultArtifactHandler$__plexus17 from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 215. ProviderInstanceBinding{key=Key[type=org.sonatype.nexus.index.context.IndexCreator, annotation=@com.google.inject.name.Named(value=maven-plugin)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.sonatype.nexus.index.creator.MavenPluginArtifactInfoIndexCreator from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 216. ProviderInstanceBinding{key=Key[type=org.apache.maven.artifact.handler.ArtifactHandler, annotation=@com.google.inject.name.Named(value=maven-plugin)], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON, provider=Deferred org.apache.maven.artifact.handler.DefaultArtifactHandler$__plexus11 from ClassRealm[plexus.core, parent: null]} 
2016-03-12 21:52:03,730 [ 340449]   INFO - ution.rmi.RemoteProcessSupport - 217. ProviderInstanceBinding{key=Key[type=org.codehaus.plexus.logging.LoggerManager, annotation=[none]], source=org.codehaus.plexus.DefaultPlexusContainer$DefaultsModule.configure(DefaultPlexusContainer.java:826), scope=Scopes.NO_SCOPE, provider=org.codehaus.plexus.DefaultPlexusContainer$LoggerManagerProvider@393be213} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 218. ProviderInstanceBinding{key=Key[type=org.codehaus.plexus.logging.Logger, annotation=[none]], source=org.codehaus.plexus.DefaultPlexusContainer$DefaultsModule.configure(DefaultPlexusContainer.java:827), scope=Scopes.NO_SCOPE, provider=org.codehaus.plexus.DefaultPlexusContainer$LoggerProvider@7248ed95} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 219. InstanceBinding{key=Key[type=org.sonatype.guice.bean.locators.RankingFunction, annotation=@com.google.inject.name.Named(value=plexus)], source=org.codehaus.plexus.DefaultPlexusContainer$DefaultsModule.configure(DefaultPlexusContainer.java:831), instance=org.sonatype.guice.bean.locators.DefaultRankingFunction@501a1c0a} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 220. LinkedKeyBinding{key=Key[type=org.sonatype.guice.bean.locators.RankingFunction, annotation=[none]], source=org.codehaus.plexus.DefaultPlexusContainer$DefaultsModule.configure(DefaultPlexusContainer.java:832), scope=Scopes.NO_SCOPE, target=Key[type=org.sonatype.guice.bean.locators.RankingFunction, annotation=@com.google.inject.name.Named(value=plexus)]} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 221. InstanceBinding{key=Key[type=org.sonatype.guice.plexus.config.PlexusBeanConverter, annotation=[none]], source=org.codehaus.plexus.DefaultPlexusContainer$DefaultsModule.configure(DefaultPlexusContainer.java:836), instance=org.sonatype.guice.plexus.converters.PlexusXmlBeanConverter@b99010e} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 222. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.Lifecycle, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 223. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.LifecycleDebugLogger, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 224. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.MojoDescriptorCreator, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 225. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.LifecycleDependencyResolver, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 226. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.DefaultSchedules, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 227. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 228. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.BuildListCalculator, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 229. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.LifecyclePluginResolver, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 230. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.LifecycleStarter, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 231. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.MojoExecutor, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 232. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.LifecycleWeaveBuilder, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 233. ConstructorBinding{key=Key[type=org.apache.maven.eventspy.internal.EventSpyDispatcher, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 234. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.LifecycleModuleBuilder, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 235. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.BuilderCommon, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 236. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.internal.ThreadConfigurationService, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - 237. ConstructorBinding{key=Key[type=org.apache.maven.lifecycle.DefaultLifecycles, annotation=[none]], source=ClassRealm[plexus.core, parent: null], scope=Scopes.SINGLETON} 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - -----[implicit bindings]------------------------------------------------------- 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport - ------------------------------------------------------------------------------- 
2016-03-12 21:52:03,731 [ 340450]   INFO - ution.rmi.RemoteProcessSupport -  
2016-03-12 21:52:13,223 [ 349942]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 13770ms; general responsiveness: ok; EDT responsiveness: 1/13 sluggish, 1/13 very slow 
2016-03-12 21:52:29,130 [ 365849]   INFO - ntellij.KobaltProjectComponent - Syncing build file for project Project '/Users/sargunvohra/Development/Projects/PokeKotlin' PokeKotlin 
2016-03-12 21:52:29,131 [ 365850]   INFO - t.intellij.SyncBuildFileAction - Kobalt jar: /Users/sargunvohra/.kobalt/wrapper/dist/kobalt-0.666/kobalt/wrapper/kobalt-0.666.jar 
2016-03-12 21:52:29,131 [ 365850]   INFO - t.intellij.SyncBuildFileAction - sendGetDependencies 
2016-03-12 21:52:29,133 [ 365852]   WARN - t.intellij.SyncBuildFileAction - Server not started yet, sleeping a bit 
2016-03-12 21:52:29,140 [ 365859]   WARN - t.intellij.SyncBuildFileAction - Launching /Applications/IntelliJ IDEA 15.app/Contents/jre/jdk/Contents/Home/jre/bin/java -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n -jar /Users/sargunvohra/.kobalt/wrapper/dist/kobalt-0.666/kobalt/wrapper/kobalt-0.666.jar --dev --server --port 1234 
2016-03-12 21:52:29,140 [ 365859]   WARN - t.intellij.SyncBuildFileAction - Server output in: /Users/sargunvohra/Library/Caches/IntelliJIdea15/tmp/kobalt8935896610013713182.tmp 
2016-03-12 21:52:29,158 [ 365877]   INFO - t.intellij.SyncBuildFileAction - Server exiting with error 
2016-03-12 21:52:31,139 [ 367858]   WARN - t.intellij.SyncBuildFileAction - Server not started yet, sleeping a bit 
2016-03-12 21:52:33,141 [ 369860]   WARN - t.intellij.SyncBuildFileAction - Server not started yet, sleeping a bit 
2016-03-12 21:52:35,143 [ 371862]   WARN - t.intellij.SyncBuildFileAction - Server not started yet, sleeping a bit 
2016-03-12 21:52:37,146 [ 373865]   WARN - t.intellij.SyncBuildFileAction - Server not started yet, sleeping a bit 
2016-03-12 21:52:39,151 [ 375870]  ERROR - t.intellij.SyncBuildFileAction - Couldn't connect to server on port 1234 
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.beust.kobalt.intellij.SyncBuildFileAction.sendGetDependencies(SyncBuildFileAction.kt:175)
    at com.beust.kobalt.intellij.SyncBuildFileAction.access$sendGetDependencies(SyncBuildFileAction.kt:32)
    at com.beust.kobalt.intellij.SyncBuildFileAction$run$$inlined$with$lambda$2.invoke(SyncBuildFileAction.kt:61)
    at com.beust.kobalt.intellij.SyncBuildFileAction$run$$inlined$with$lambda$2.invoke(SyncBuildFileAction.kt:32)
    at com.beust.kobalt.intellij.SyncBuildFileAction$toBackgroundTask$1.run(SyncBuildFileAction.kt:69)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
2016-03-12 21:52:39,156 [ 375875]  ERROR - t.intellij.SyncBuildFileAction - IntelliJ IDEA 15.0.4  Build #IU-143.2287.1 
2016-03-12 21:52:39,156 [ 375875]  ERROR - t.intellij.SyncBuildFileAction - JDK: 1.8.0_40-release 
2016-03-12 21:52:39,156 [ 375875]  ERROR - t.intellij.SyncBuildFileAction - VM: OpenJDK 64-Bit Server VM 
2016-03-12 21:52:39,156 [ 375875]  ERROR - t.intellij.SyncBuildFileAction - Vendor: JetBrains s.r.o 
2016-03-12 21:52:39,156 [ 375875]  ERROR - t.intellij.SyncBuildFileAction - OS: Mac OS X 
2016-03-12 21:52:39,156 [ 375875]  ERROR - t.intellij.SyncBuildFileAction - Last Action: kobalt.SyncBuildFile 

```

**Comment by dmitry-zhuravlev** [comment]
@sargunster Does this issue still valid for you?

**Comment by sargunv** [comment]
Nope, I haven't had it happen in a long time.

**Comment by dmitry-zhuravlev** [comment]
Thanks for feedback!
