### ISSUE TITLE
Intellij IDEA project isn't synced ("projectDataManager must not be null")

### ISSUE THREAD

**Issue by dector** [cbeust/kobalt-intellij-plugin#83]
__Steps to reproduce__:

1. Create new kobalt project (with kotlin sources)
```bash
$ kobaltw --version
Kobalt 1.0.87, Wrapper 1.0.87

$ mkdir kobalt_test; cd kobalt_test/
$ kobaltw --init kotlin
            _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  1.0.87

  Regular compilation time: 1619 ms


Template "kotlin" installed
Now you can run either `./kobaltw test` or `./kobaltw run`
```

2. Open project is Intellij IDEA (with installed plugin v1.128).
3. `Tools` -> `Kobalt` -> `Find detached Kobalt project`.
4. Click on `Import Kobal project` in displayed popup with title `Detached Kobal project found`.

__Expected result__:
Kobalt project is synced with Intellij IDEA.

__Actual result__:
IDE fatal error ocurred. See full stack trace:

```
projectDataManager must not be null
java.lang.IllegalStateException: projectDataManager must not be null
	at com.beust.kobalt.intellij.notification.KobaltNotificationUtilsKt$showNotificationForUnlinkedkobaltProject$1.hyperlinkActivated(KobaltNotificationUtils.kt:50)
	at com.intellij.notification.NotificationListener$Adapter.hyperlinkUpdate(NotificationListener.java:31)
	at com.intellij.notification.impl.ui.NotificationsUtil$1.hyperlinkUpdate(NotificationsUtil.java:155)
	at javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:342)
	at javax.swing.text.html.HTMLEditorKit$LinkController.activateLink(HTMLEditorKit.java:875)
	at javax.swing.text.html.HTMLEditorKit$LinkController.mouseClicked(HTMLEditorKit.java:674)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

__Used software__:
Kobalt - 1.0.87 (both app and wrapper)
Kobal Intellij IDEA plugin - 1.128
IntelliJ IDEA - 2017.2 (Build #IC-172.3317.76, built on July 15, 2017)

**Comment by dmitry-zhuravlev** [comment]
@dector Init IDEA project from Kobalt is deprecated. Please use IDEA directly to setup Kobalt project.

**Comment by dmitry-zhuravlev** [comment]
@dector sorry, I mean "init idea" is something that should be deprecated, but as far as I can see you are using "init kotlin" parameters. I'll take a look. Anyway you still can create Kobalt project directly fron IDEA without using comand line at all.

**Comment by dector** [comment]
@dmitry-zhuravlev Thanks. Suggested option to create kobalt project within IDEA works.
Ping me if you'll need some help with additional debuggin for this issue.

**Comment by dector** [comment]
@dmitry-zhuravlev Issue isn't reproducible on v1.129. Thanks a lot!

**Comment by dmitry-zhuravlev** [comment]
@dector Thanks for fill detailed issue and for retest ;)
