### ISSUE TITLE
Fails to import/sync on 2018.1 EAP

### ISSUE THREAD

**Issue by jkbbwr** [cbeust/kobalt-intellij-plugin#89]
Fails to import/sync on 2018.1 EAP with the following error

```
java.lang.ExceptionInInitializerError
	at com.intellij.externalSystem.JavaProjectData.<clinit>(JavaProjectData.java:44)
	at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.doResolveProjectInfo(KobaltProjectResolver.kt:57)
	at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.resolveProjectInfo(KobaltProjectResolver.kt:49)
	at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.resolveProjectInfo(KobaltProjectResolver.kt:37)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.a(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:58)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.openapi.externalSystem.service.RemoteExternalSystemFacadeImpl$1.invoke(RemoteExternalSystemFacadeImpl.java:115)
	at com.sun.proxy.$Proxy3.resolveProjectInfo(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.MissingResourceException: Can't find bundle for base name messages.JavaCoreBundle, locale en_GB
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at com.intellij.core.JavaCoreBundle.getBundle(JavaCoreBundle.java:45)
	at com.intellij.core.JavaCoreBundle.message(JavaCoreBundle.java:33)
	at com.intellij.pom.java.LanguageLevel.<clinit>(LanguageLevel.java:24)
	... 30 more


```

**Comment by pabl0rg** [comment]
I've got the same problem now that intellij 2018.1 is out (no longer EAP)

**Comment by pabl0rg** [comment]
There are no localized versions of JavaCoreBundle.properties

https://github.com/JetBrains/intellij-community/tree/master/java/java-psi-api/src/messages

But one would think that the default is enough

**Comment by pabl0rg** [comment]
I opened an issue on the IJ youtrack and they closed it indicating that this should be handled by the plugin.

https://youtrack.jetbrains.com/issue/IDEA-191059

**Comment by dmitry-zhuravlev** [comment]
I think that duplicating core bundle messages inside plugin not a good idea but we can leave it as a workaround.
